
## Keypoint detection
# Radius for non maxima supression in Harris keypoints detector
harris_kps_radius: 0.5

# Radius for normals estimation
normals_radius: .5

# threshold value for detecting corners in Harris keypoints detector
harris_kps_thres: 1e-6

## Feature computation
# Radius for SHOT computation
shot_feats_radius: 40.

# Radius for normals estimation
normals_feats_radius: 40.

# Radius for external local reference frames computation
lrf_feats_radius: 40.

## Correspondence matching
# maximum allowed distance between correspondences in keypoints
kps_cor_thres: 30.0

# maximum allowed distance between correspondences in features
feats_cor_thres: 40.0

## Clustering 
k_means_clusters: 3
